import {
  LayoutDashboard,
  Users,
  GraduationCap,
  Wallet,
  CalendarCheck,
  BookOpen,
  FileText,
  BarChart3,
  Settings,
  Bell,
  MessageSquare,
  UserCheck,
  ClipboardList,
  CreditCard,
  TrendingUp,
  Shield,
  Building,
  Award,
  Bus,
  Library,
  Bed,
  Camera,
  UserPlus,
  Search,
  Clock,
  Target,
  Presentation,
  AlertCircle,
  Mail,
  Phone,
  Globe,
  Key,
  Database,
  History,
  Download,
  Upload,
  Palette,
  Lock,
  Eye,
  ChevronRight,
  LogOut,
  User,
  Home,
  BookMarked,
  TestTube,
  Calendar,
  Receipt,
  PieChart,
  FolderOpen,
  Video,
  HelpCircle,
  Info,
  Star,
  Megaphone,
  Newspaper,
  Image,
  SlidersHorizontal,
  UserCog,
  UsersRound,
  Baby,
  Calculator,
  School,
  Trophy,
  Package,
  Ticket,
  FileSpreadsheet,
  MapPin,
  PhoneCall,
  MessageCircle,
  Send,
  Bot,
  Sparkles,
  Zap,
  CheckCircle,
  XCircle,
  AlertTriangle,
  InfoIcon,
  ArrowUpRight,
  ArrowDownRight,
  MoreHorizontal,
  Filter,
  Plus,
  Edit,
  Trash,
  Save,
  X,
  ChevronDown,
  ChevronLeft,
  Menu,
  Moon,
  Sun,
  SearchIcon,
  Command,
  Globe2,
} from 'lucide-react';

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  BRANCH_ADMIN: 'branch_admin',
  TEACHER: 'teacher',
  STUDENT: 'student',
  PARENT: 'parent',
  RECEPTIONIST: 'receptionist',
  ACCOUNTANT: 'accountant',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export interface MenuItem {
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  path: string;
  roles: Role[];
  badge?: string | number;
  children?: MenuItem[];
}

export const MENU_ITEMS: MenuItem[] = [
  {
    title: 'Dashboard',
    icon: LayoutDashboard,
    path: '/dashboard',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT, ROLES.ACCOUNTANT],
  },
  {
    title: 'Students',
    icon: Users,
    path: '/admin/students',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.RECEPTIONIST, ROLES.TEACHER],
  },
  {
    title: 'Teachers',
    icon: UserCheck,
    path: '/admin/teachers',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  },
  {
    title: 'Parents',
    icon: UsersRound,
    path: '/admin/parents',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  },
  {
    title: 'Admissions',
    icon: UserPlus,
    path: '/admin/admissions',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.RECEPTIONIST],
  },
  {
    title: 'Courses',
    icon: BookOpen,
    path: '/admin/courses',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER],
  },
  {
    title: 'Attendance',
    icon: CalendarCheck,
    path: '/admin/attendance',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    title: 'Exams & Results',
    icon: Award,
    path: '/admin/exams',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    title: 'Homework',
    icon: FileText,
    path: '/admin/homework',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    title: 'Assignments',
    icon: ClipboardList,
    path: '/admin/assignments',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    title: 'LMS',
    icon: BookMarked,
    path: '/admin/lms',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT],
  },
  {
    title: 'Live Classes',
    icon: Video,
    path: '/admin/live',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT],
  },
  {
    title: 'Fee Management',
    icon: Wallet,
    path: '/admin/payments',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.ACCOUNTANT, ROLES.RECEPTIONIST, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    title: 'Accounting',
    icon: Calculator,
    path: '/admin/accounting',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.ACCOUNTANT],
  },
  {
    title: 'Reports',
    icon: BarChart3,
    path: '/admin/reports',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.ACCOUNTANT],
  },
  {
    title: 'Analytics',
    icon: TrendingUp,
    path: '/admin/analytics',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  },
  {
    title: 'Notices & Events',
    icon: Bell,
    path: '/admin/notices',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    title: 'Library',
    icon: Library,
    path: '/admin/library',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  },
  {
    title: 'Transport',
    icon: Bus,
    path: '/admin/transport',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  },
  {
    title: 'Hostel',
    icon: Bed,
    path: '/admin/hostel',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  },
  {
    title: 'ID Cards',
    icon: CreditCard,
    path: '/admin/id-cards',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.RECEPTIONIST],
  },
  {
    title: 'Certificates',
    icon: Award,
    path: '/admin/certificates',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  },
  {
    title: 'Branches',
    icon: Building,
    path: '/admin/branches',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    title: 'Users & Roles',
    icon: Shield,
    path: '/admin/users',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    title: 'Settings',
    icon: Settings,
    path: '/admin/settings',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN],
  },
  {
    title: 'Profile',
    icon: User,
    path: '/admin/profile',
    roles: [ROLES.SUPER_ADMIN, ROLES.BRANCH_ADMIN, ROLES.TEACHER, ROLES.STUDENT, ROLES.PARENT, ROLES.ACCOUNTANT, ROLES.RECEPTIONIST],
  },
];

export function getMenuItemsForRole(role: Role): MenuItem[] {
  return MENU_ITEMS.filter((item) => item.roles.includes(role));
}

export function hasAccess(role: Role, path: string): boolean {
  return MENU_ITEMS.some((item) => item.path === path && item.roles.includes(role));
}
