/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTransportRouteImport } from './routes/_authenticated/admin.transport'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin.teachers'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminResultsRouteImport } from './routes/_authenticated/admin.results'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminReceptionRouteImport } from './routes/_authenticated/admin.reception'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminParentsRouteImport } from './routes/_authenticated/admin.parents'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin.notices'
import { Route as AuthenticatedAdminLiveRouteImport } from './routes/_authenticated/admin.live'
import { Route as AuthenticatedAdminLibraryRouteImport } from './routes/_authenticated/admin.library'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminIdCardsRouteImport } from './routes/_authenticated/admin.id-cards'
import { Route as AuthenticatedAdminHostelRouteImport } from './routes/_authenticated/admin.hostel'
import { Route as AuthenticatedAdminHomeworkRouteImport } from './routes/_authenticated/admin.homework'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin.branches'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin.attendance'
import { Route as AuthenticatedAdminAssignmentsRouteImport } from './routes/_authenticated/admin.assignments'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin.api-keys'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminAdmissionsRouteImport } from './routes/_authenticated/admin.admissions'
import { Route as AuthenticatedAdminAccountingRouteImport } from './routes/_authenticated/admin.accounting'
import { Route as AuthenticatedAdminMarketingWhatsappRouteImport } from './routes/_authenticated/admin.marketing.whatsapp'
import { Route as AuthenticatedAdminMarketingSmsRouteImport } from './routes/_authenticated/admin.marketing.sms'
import { Route as AuthenticatedAdminMarketingPushRouteImport } from './routes/_authenticated/admin.marketing.push'
import { Route as AuthenticatedAdminMarketingEmailRouteImport } from './routes/_authenticated/admin.marketing.email'
import { Route as AuthenticatedAdminHrPayrollRouteImport } from './routes/_authenticated/admin.hr.payroll'
import { Route as AuthenticatedAdminHrLeavesRouteImport } from './routes/_authenticated/admin.hr.leaves'
import { Route as AuthenticatedAdminHrEmployeesRouteImport } from './routes/_authenticated/admin.hr.employees'
import { Route as AuthenticatedAdminHrDepartmentsRouteImport } from './routes/_authenticated/admin.hr.departments'
import { Route as AuthenticatedAdminCrmVisitorsRouteImport } from './routes/_authenticated/admin.crm.visitors'
import { Route as AuthenticatedAdminCrmLeadsRouteImport } from './routes/_authenticated/admin.crm.leads'
import { Route as AuthenticatedAdminCrmInquiriesRouteImport } from './routes/_authenticated/admin.crm.inquiries'
import { Route as AuthenticatedAdminCrmCounsellingRouteImport } from './routes/_authenticated/admin.crm.counselling'
import { Route as AuthenticatedAdminCmsWebsiteRouteImport } from './routes/_authenticated/admin.cms.website'
import { Route as AuthenticatedAdminCmsTestimonialsRouteImport } from './routes/_authenticated/admin.cms.testimonials'
import { Route as AuthenticatedAdminCmsSeoRouteImport } from './routes/_authenticated/admin.cms.seo'
import { Route as AuthenticatedAdminCmsFaqRouteImport } from './routes/_authenticated/admin.cms.faq'
import { Route as AuthenticatedAdminCmsEventsRouteImport } from './routes/_authenticated/admin.cms.events'
import { Route as AuthenticatedAdminCmsBlogsRouteImport } from './routes/_authenticated/admin.cms.blogs'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTransportRoute =
  AuthenticatedAdminTransportRouteImport.update({
    id: '/transport',
    path: '/transport',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminResultsRoute =
  AuthenticatedAdminResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReceptionRoute =
  AuthenticatedAdminReceptionRouteImport.update({
    id: '/reception',
    path: '/reception',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParentsRoute =
  AuthenticatedAdminParentsRouteImport.update({
    id: '/parents',
    path: '/parents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiveRoute = AuthenticatedAdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLibraryRoute =
  AuthenticatedAdminLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIdCardsRoute =
  AuthenticatedAdminIdCardsRouteImport.update({
    id: '/id-cards',
    path: '/id-cards',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHostelRoute =
  AuthenticatedAdminHostelRouteImport.update({
    id: '/hostel',
    path: '/hostel',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomeworkRoute =
  AuthenticatedAdminHomeworkRouteImport.update({
    id: '/homework',
    path: '/homework',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssignmentsRoute =
  AuthenticatedAdminAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdmissionsRoute =
  AuthenticatedAdminAdmissionsRouteImport.update({
    id: '/admissions',
    path: '/admissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountingRoute =
  AuthenticatedAdminAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingWhatsappRoute =
  AuthenticatedAdminMarketingWhatsappRouteImport.update({
    id: '/marketing/whatsapp',
    path: '/marketing/whatsapp',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingSmsRoute =
  AuthenticatedAdminMarketingSmsRouteImport.update({
    id: '/marketing/sms',
    path: '/marketing/sms',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingPushRoute =
  AuthenticatedAdminMarketingPushRouteImport.update({
    id: '/marketing/push',
    path: '/marketing/push',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingEmailRoute =
  AuthenticatedAdminMarketingEmailRouteImport.update({
    id: '/marketing/email',
    path: '/marketing/email',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrPayrollRoute =
  AuthenticatedAdminHrPayrollRouteImport.update({
    id: '/hr/payroll',
    path: '/hr/payroll',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrLeavesRoute =
  AuthenticatedAdminHrLeavesRouteImport.update({
    id: '/hr/leaves',
    path: '/hr/leaves',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrEmployeesRoute =
  AuthenticatedAdminHrEmployeesRouteImport.update({
    id: '/hr/employees',
    path: '/hr/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrDepartmentsRoute =
  AuthenticatedAdminHrDepartmentsRouteImport.update({
    id: '/hr/departments',
    path: '/hr/departments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmVisitorsRoute =
  AuthenticatedAdminCrmVisitorsRouteImport.update({
    id: '/crm/visitors',
    path: '/crm/visitors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmLeadsRoute =
  AuthenticatedAdminCrmLeadsRouteImport.update({
    id: '/crm/leads',
    path: '/crm/leads',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmInquiriesRoute =
  AuthenticatedAdminCrmInquiriesRouteImport.update({
    id: '/crm/inquiries',
    path: '/crm/inquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmCounsellingRoute =
  AuthenticatedAdminCrmCounsellingRouteImport.update({
    id: '/crm/counselling',
    path: '/crm/counselling',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsWebsiteRoute =
  AuthenticatedAdminCmsWebsiteRouteImport.update({
    id: '/cms/website',
    path: '/cms/website',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsTestimonialsRoute =
  AuthenticatedAdminCmsTestimonialsRouteImport.update({
    id: '/cms/testimonials',
    path: '/cms/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsSeoRoute =
  AuthenticatedAdminCmsSeoRouteImport.update({
    id: '/cms/seo',
    path: '/cms/seo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsFaqRoute =
  AuthenticatedAdminCmsFaqRouteImport.update({
    id: '/cms/faq',
    path: '/cms/faq',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsEventsRoute =
  AuthenticatedAdminCmsEventsRouteImport.update({
    id: '/cms/events',
    path: '/cms/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsBlogsRoute =
  AuthenticatedAdminCmsBlogsRouteImport.update({
    id: '/cms/blogs',
    path: '/cms/blogs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/results': typeof ResultsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/accounting': typeof AuthenticatedAdminAccountingRoute
  '/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/admin/hostel': typeof AuthenticatedAdminHostelRoute
  '/admin/id-cards': typeof AuthenticatedAdminIdCardsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/reception': typeof AuthenticatedAdminReceptionRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/results': typeof AuthenticatedAdminResultsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/transport': typeof AuthenticatedAdminTransportRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cms/blogs': typeof AuthenticatedAdminCmsBlogsRoute
  '/admin/cms/events': typeof AuthenticatedAdminCmsEventsRoute
  '/admin/cms/faq': typeof AuthenticatedAdminCmsFaqRoute
  '/admin/cms/seo': typeof AuthenticatedAdminCmsSeoRoute
  '/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/admin/cms/website': typeof AuthenticatedAdminCmsWebsiteRoute
  '/admin/crm/counselling': typeof AuthenticatedAdminCrmCounsellingRoute
  '/admin/crm/inquiries': typeof AuthenticatedAdminCrmInquiriesRoute
  '/admin/crm/leads': typeof AuthenticatedAdminCrmLeadsRoute
  '/admin/crm/visitors': typeof AuthenticatedAdminCrmVisitorsRoute
  '/admin/hr/departments': typeof AuthenticatedAdminHrDepartmentsRoute
  '/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/admin/hr/leaves': typeof AuthenticatedAdminHrLeavesRoute
  '/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/admin/marketing/email': typeof AuthenticatedAdminMarketingEmailRoute
  '/admin/marketing/push': typeof AuthenticatedAdminMarketingPushRoute
  '/admin/marketing/sms': typeof AuthenticatedAdminMarketingSmsRoute
  '/admin/marketing/whatsapp': typeof AuthenticatedAdminMarketingWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/results': typeof ResultsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/accounting': typeof AuthenticatedAdminAccountingRoute
  '/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/admin/hostel': typeof AuthenticatedAdminHostelRoute
  '/admin/id-cards': typeof AuthenticatedAdminIdCardsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/reception': typeof AuthenticatedAdminReceptionRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/results': typeof AuthenticatedAdminResultsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/transport': typeof AuthenticatedAdminTransportRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cms/blogs': typeof AuthenticatedAdminCmsBlogsRoute
  '/admin/cms/events': typeof AuthenticatedAdminCmsEventsRoute
  '/admin/cms/faq': typeof AuthenticatedAdminCmsFaqRoute
  '/admin/cms/seo': typeof AuthenticatedAdminCmsSeoRoute
  '/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/admin/cms/website': typeof AuthenticatedAdminCmsWebsiteRoute
  '/admin/crm/counselling': typeof AuthenticatedAdminCrmCounsellingRoute
  '/admin/crm/inquiries': typeof AuthenticatedAdminCrmInquiriesRoute
  '/admin/crm/leads': typeof AuthenticatedAdminCrmLeadsRoute
  '/admin/crm/visitors': typeof AuthenticatedAdminCrmVisitorsRoute
  '/admin/hr/departments': typeof AuthenticatedAdminHrDepartmentsRoute
  '/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/admin/hr/leaves': typeof AuthenticatedAdminHrLeavesRoute
  '/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/admin/marketing/email': typeof AuthenticatedAdminMarketingEmailRoute
  '/admin/marketing/push': typeof AuthenticatedAdminMarketingPushRoute
  '/admin/marketing/sms': typeof AuthenticatedAdminMarketingSmsRoute
  '/admin/marketing/whatsapp': typeof AuthenticatedAdminMarketingWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/results': typeof ResultsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/accounting': typeof AuthenticatedAdminAccountingRoute
  '/_authenticated/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/_authenticated/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/_authenticated/admin/hostel': typeof AuthenticatedAdminHostelRoute
  '/_authenticated/admin/id-cards': typeof AuthenticatedAdminIdCardsRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/_authenticated/admin/live': typeof AuthenticatedAdminLiveRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/reception': typeof AuthenticatedAdminReceptionRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/results': typeof AuthenticatedAdminResultsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/admin/transport': typeof AuthenticatedAdminTransportRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cms/blogs': typeof AuthenticatedAdminCmsBlogsRoute
  '/_authenticated/admin/cms/events': typeof AuthenticatedAdminCmsEventsRoute
  '/_authenticated/admin/cms/faq': typeof AuthenticatedAdminCmsFaqRoute
  '/_authenticated/admin/cms/seo': typeof AuthenticatedAdminCmsSeoRoute
  '/_authenticated/admin/cms/testimonials': typeof AuthenticatedAdminCmsTestimonialsRoute
  '/_authenticated/admin/cms/website': typeof AuthenticatedAdminCmsWebsiteRoute
  '/_authenticated/admin/crm/counselling': typeof AuthenticatedAdminCrmCounsellingRoute
  '/_authenticated/admin/crm/inquiries': typeof AuthenticatedAdminCrmInquiriesRoute
  '/_authenticated/admin/crm/leads': typeof AuthenticatedAdminCrmLeadsRoute
  '/_authenticated/admin/crm/visitors': typeof AuthenticatedAdminCrmVisitorsRoute
  '/_authenticated/admin/hr/departments': typeof AuthenticatedAdminHrDepartmentsRoute
  '/_authenticated/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/_authenticated/admin/hr/leaves': typeof AuthenticatedAdminHrLeavesRoute
  '/_authenticated/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/_authenticated/admin/marketing/email': typeof AuthenticatedAdminMarketingEmailRoute
  '/_authenticated/admin/marketing/push': typeof AuthenticatedAdminMarketingPushRoute
  '/_authenticated/admin/marketing/sms': typeof AuthenticatedAdminMarketingSmsRoute
  '/_authenticated/admin/marketing/whatsapp': typeof AuthenticatedAdminMarketingWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/faculty'
    | '/gallery'
    | '/results'
    | '/admin'
    | '/dashboard'
    | '/admin/accounting'
    | '/admin/admissions'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/assignments'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/banners'
    | '/admin/branches'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/exams'
    | '/admin/homework'
    | '/admin/hostel'
    | '/admin/id-cards'
    | '/admin/integrations'
    | '/admin/library'
    | '/admin/live'
    | '/admin/notices'
    | '/admin/parents'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/reception'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/support'
    | '/admin/teachers'
    | '/admin/transport'
    | '/admin/'
    | '/admin/cms/blogs'
    | '/admin/cms/events'
    | '/admin/cms/faq'
    | '/admin/cms/seo'
    | '/admin/cms/testimonials'
    | '/admin/cms/website'
    | '/admin/crm/counselling'
    | '/admin/crm/inquiries'
    | '/admin/crm/leads'
    | '/admin/crm/visitors'
    | '/admin/hr/departments'
    | '/admin/hr/employees'
    | '/admin/hr/leaves'
    | '/admin/hr/payroll'
    | '/admin/marketing/email'
    | '/admin/marketing/push'
    | '/admin/marketing/sms'
    | '/admin/marketing/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/faculty'
    | '/gallery'
    | '/results'
    | '/dashboard'
    | '/admin/accounting'
    | '/admin/admissions'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/assignments'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/banners'
    | '/admin/branches'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/exams'
    | '/admin/homework'
    | '/admin/hostel'
    | '/admin/id-cards'
    | '/admin/integrations'
    | '/admin/library'
    | '/admin/live'
    | '/admin/notices'
    | '/admin/parents'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/reception'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/support'
    | '/admin/teachers'
    | '/admin/transport'
    | '/admin'
    | '/admin/cms/blogs'
    | '/admin/cms/events'
    | '/admin/cms/faq'
    | '/admin/cms/seo'
    | '/admin/cms/testimonials'
    | '/admin/cms/website'
    | '/admin/crm/counselling'
    | '/admin/crm/inquiries'
    | '/admin/crm/leads'
    | '/admin/crm/visitors'
    | '/admin/hr/departments'
    | '/admin/hr/employees'
    | '/admin/hr/leaves'
    | '/admin/hr/payroll'
    | '/admin/marketing/email'
    | '/admin/marketing/push'
    | '/admin/marketing/sms'
    | '/admin/marketing/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admission'
    | '/auth'
    | '/contact'
    | '/courses'
    | '/faculty'
    | '/gallery'
    | '/results'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/accounting'
    | '/_authenticated/admin/admissions'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/assignments'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/homework'
    | '/_authenticated/admin/hostel'
    | '/_authenticated/admin/id-cards'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/library'
    | '/_authenticated/admin/live'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/parents'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/reception'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/results'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/admin/transport'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cms/blogs'
    | '/_authenticated/admin/cms/events'
    | '/_authenticated/admin/cms/faq'
    | '/_authenticated/admin/cms/seo'
    | '/_authenticated/admin/cms/testimonials'
    | '/_authenticated/admin/cms/website'
    | '/_authenticated/admin/crm/counselling'
    | '/_authenticated/admin/crm/inquiries'
    | '/_authenticated/admin/crm/leads'
    | '/_authenticated/admin/crm/visitors'
    | '/_authenticated/admin/hr/departments'
    | '/_authenticated/admin/hr/employees'
    | '/_authenticated/admin/hr/leaves'
    | '/_authenticated/admin/hr/payroll'
    | '/_authenticated/admin/marketing/email'
    | '/_authenticated/admin/marketing/push'
    | '/_authenticated/admin/marketing/sms'
    | '/_authenticated/admin/marketing/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  ResultsRoute: typeof ResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transport': {
      id: '/_authenticated/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AuthenticatedAdminTransportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/results': {
      id: '/_authenticated/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AuthenticatedAdminResultsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reception': {
      id: '/_authenticated/admin/reception'
      path: '/reception'
      fullPath: '/admin/reception'
      preLoaderRoute: typeof AuthenticatedAdminReceptionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parents': {
      id: '/_authenticated/admin/parents'
      path: '/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AuthenticatedAdminParentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live': {
      id: '/_authenticated/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AuthenticatedAdminLiveRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/library': {
      id: '/_authenticated/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AuthenticatedAdminLibraryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/id-cards': {
      id: '/_authenticated/admin/id-cards'
      path: '/id-cards'
      fullPath: '/admin/id-cards'
      preLoaderRoute: typeof AuthenticatedAdminIdCardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hostel': {
      id: '/_authenticated/admin/hostel'
      path: '/hostel'
      fullPath: '/admin/hostel'
      preLoaderRoute: typeof AuthenticatedAdminHostelRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homework': {
      id: '/_authenticated/admin/homework'
      path: '/homework'
      fullPath: '/admin/homework'
      preLoaderRoute: typeof AuthenticatedAdminHomeworkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assignments': {
      id: '/_authenticated/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admissions': {
      id: '/_authenticated/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AuthenticatedAdminAdmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/accounting': {
      id: '/_authenticated/admin/accounting'
      path: '/accounting'
      fullPath: '/admin/accounting'
      preLoaderRoute: typeof AuthenticatedAdminAccountingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing/whatsapp': {
      id: '/_authenticated/admin/marketing/whatsapp'
      path: '/marketing/whatsapp'
      fullPath: '/admin/marketing/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminMarketingWhatsappRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing/sms': {
      id: '/_authenticated/admin/marketing/sms'
      path: '/marketing/sms'
      fullPath: '/admin/marketing/sms'
      preLoaderRoute: typeof AuthenticatedAdminMarketingSmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing/push': {
      id: '/_authenticated/admin/marketing/push'
      path: '/marketing/push'
      fullPath: '/admin/marketing/push'
      preLoaderRoute: typeof AuthenticatedAdminMarketingPushRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing/email': {
      id: '/_authenticated/admin/marketing/email'
      path: '/marketing/email'
      fullPath: '/admin/marketing/email'
      preLoaderRoute: typeof AuthenticatedAdminMarketingEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/payroll': {
      id: '/_authenticated/admin/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/admin/hr/payroll'
      preLoaderRoute: typeof AuthenticatedAdminHrPayrollRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/leaves': {
      id: '/_authenticated/admin/hr/leaves'
      path: '/hr/leaves'
      fullPath: '/admin/hr/leaves'
      preLoaderRoute: typeof AuthenticatedAdminHrLeavesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/employees': {
      id: '/_authenticated/admin/hr/employees'
      path: '/hr/employees'
      fullPath: '/admin/hr/employees'
      preLoaderRoute: typeof AuthenticatedAdminHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/departments': {
      id: '/_authenticated/admin/hr/departments'
      path: '/hr/departments'
      fullPath: '/admin/hr/departments'
      preLoaderRoute: typeof AuthenticatedAdminHrDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm/visitors': {
      id: '/_authenticated/admin/crm/visitors'
      path: '/crm/visitors'
      fullPath: '/admin/crm/visitors'
      preLoaderRoute: typeof AuthenticatedAdminCrmVisitorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm/leads': {
      id: '/_authenticated/admin/crm/leads'
      path: '/crm/leads'
      fullPath: '/admin/crm/leads'
      preLoaderRoute: typeof AuthenticatedAdminCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm/inquiries': {
      id: '/_authenticated/admin/crm/inquiries'
      path: '/crm/inquiries'
      fullPath: '/admin/crm/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminCrmInquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm/counselling': {
      id: '/_authenticated/admin/crm/counselling'
      path: '/crm/counselling'
      fullPath: '/admin/crm/counselling'
      preLoaderRoute: typeof AuthenticatedAdminCrmCounsellingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/website': {
      id: '/_authenticated/admin/cms/website'
      path: '/cms/website'
      fullPath: '/admin/cms/website'
      preLoaderRoute: typeof AuthenticatedAdminCmsWebsiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/testimonials': {
      id: '/_authenticated/admin/cms/testimonials'
      path: '/cms/testimonials'
      fullPath: '/admin/cms/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminCmsTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/seo': {
      id: '/_authenticated/admin/cms/seo'
      path: '/cms/seo'
      fullPath: '/admin/cms/seo'
      preLoaderRoute: typeof AuthenticatedAdminCmsSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/faq': {
      id: '/_authenticated/admin/cms/faq'
      path: '/cms/faq'
      fullPath: '/admin/cms/faq'
      preLoaderRoute: typeof AuthenticatedAdminCmsFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/events': {
      id: '/_authenticated/admin/cms/events'
      path: '/cms/events'
      fullPath: '/admin/cms/events'
      preLoaderRoute: typeof AuthenticatedAdminCmsEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/blogs': {
      id: '/_authenticated/admin/cms/blogs'
      path: '/cms/blogs'
      fullPath: '/admin/cms/blogs'
      preLoaderRoute: typeof AuthenticatedAdminCmsBlogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccountingRoute: typeof AuthenticatedAdminAccountingRoute
  AuthenticatedAdminAdmissionsRoute: typeof AuthenticatedAdminAdmissionsRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminAssignmentsRoute: typeof AuthenticatedAdminAssignmentsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRoute
  AuthenticatedAdminHomeworkRoute: typeof AuthenticatedAdminHomeworkRoute
  AuthenticatedAdminHostelRoute: typeof AuthenticatedAdminHostelRoute
  AuthenticatedAdminIdCardsRoute: typeof AuthenticatedAdminIdCardsRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminLibraryRoute: typeof AuthenticatedAdminLibraryRoute
  AuthenticatedAdminLiveRoute: typeof AuthenticatedAdminLiveRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminParentsRoute: typeof AuthenticatedAdminParentsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminReceptionRoute: typeof AuthenticatedAdminReceptionRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminResultsRoute: typeof AuthenticatedAdminResultsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminTransportRoute: typeof AuthenticatedAdminTransportRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCmsBlogsRoute: typeof AuthenticatedAdminCmsBlogsRoute
  AuthenticatedAdminCmsEventsRoute: typeof AuthenticatedAdminCmsEventsRoute
  AuthenticatedAdminCmsFaqRoute: typeof AuthenticatedAdminCmsFaqRoute
  AuthenticatedAdminCmsSeoRoute: typeof AuthenticatedAdminCmsSeoRoute
  AuthenticatedAdminCmsTestimonialsRoute: typeof AuthenticatedAdminCmsTestimonialsRoute
  AuthenticatedAdminCmsWebsiteRoute: typeof AuthenticatedAdminCmsWebsiteRoute
  AuthenticatedAdminCrmCounsellingRoute: typeof AuthenticatedAdminCrmCounsellingRoute
  AuthenticatedAdminCrmInquiriesRoute: typeof AuthenticatedAdminCrmInquiriesRoute
  AuthenticatedAdminCrmLeadsRoute: typeof AuthenticatedAdminCrmLeadsRoute
  AuthenticatedAdminCrmVisitorsRoute: typeof AuthenticatedAdminCrmVisitorsRoute
  AuthenticatedAdminHrDepartmentsRoute: typeof AuthenticatedAdminHrDepartmentsRoute
  AuthenticatedAdminHrEmployeesRoute: typeof AuthenticatedAdminHrEmployeesRoute
  AuthenticatedAdminHrLeavesRoute: typeof AuthenticatedAdminHrLeavesRoute
  AuthenticatedAdminHrPayrollRoute: typeof AuthenticatedAdminHrPayrollRoute
  AuthenticatedAdminMarketingEmailRoute: typeof AuthenticatedAdminMarketingEmailRoute
  AuthenticatedAdminMarketingPushRoute: typeof AuthenticatedAdminMarketingPushRoute
  AuthenticatedAdminMarketingSmsRoute: typeof AuthenticatedAdminMarketingSmsRoute
  AuthenticatedAdminMarketingWhatsappRoute: typeof AuthenticatedAdminMarketingWhatsappRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccountingRoute: AuthenticatedAdminAccountingRoute,
  AuthenticatedAdminAdmissionsRoute: AuthenticatedAdminAdmissionsRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminAssignmentsRoute: AuthenticatedAdminAssignmentsRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRoute,
  AuthenticatedAdminHomeworkRoute: AuthenticatedAdminHomeworkRoute,
  AuthenticatedAdminHostelRoute: AuthenticatedAdminHostelRoute,
  AuthenticatedAdminIdCardsRoute: AuthenticatedAdminIdCardsRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminLibraryRoute: AuthenticatedAdminLibraryRoute,
  AuthenticatedAdminLiveRoute: AuthenticatedAdminLiveRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminParentsRoute: AuthenticatedAdminParentsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminReceptionRoute: AuthenticatedAdminReceptionRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminResultsRoute: AuthenticatedAdminResultsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedAdminTransportRoute: AuthenticatedAdminTransportRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCmsBlogsRoute: AuthenticatedAdminCmsBlogsRoute,
  AuthenticatedAdminCmsEventsRoute: AuthenticatedAdminCmsEventsRoute,
  AuthenticatedAdminCmsFaqRoute: AuthenticatedAdminCmsFaqRoute,
  AuthenticatedAdminCmsSeoRoute: AuthenticatedAdminCmsSeoRoute,
  AuthenticatedAdminCmsTestimonialsRoute:
    AuthenticatedAdminCmsTestimonialsRoute,
  AuthenticatedAdminCmsWebsiteRoute: AuthenticatedAdminCmsWebsiteRoute,
  AuthenticatedAdminCrmCounsellingRoute: AuthenticatedAdminCrmCounsellingRoute,
  AuthenticatedAdminCrmInquiriesRoute: AuthenticatedAdminCrmInquiriesRoute,
  AuthenticatedAdminCrmLeadsRoute: AuthenticatedAdminCrmLeadsRoute,
  AuthenticatedAdminCrmVisitorsRoute: AuthenticatedAdminCrmVisitorsRoute,
  AuthenticatedAdminHrDepartmentsRoute: AuthenticatedAdminHrDepartmentsRoute,
  AuthenticatedAdminHrEmployeesRoute: AuthenticatedAdminHrEmployeesRoute,
  AuthenticatedAdminHrLeavesRoute: AuthenticatedAdminHrLeavesRoute,
  AuthenticatedAdminHrPayrollRoute: AuthenticatedAdminHrPayrollRoute,
  AuthenticatedAdminMarketingEmailRoute: AuthenticatedAdminMarketingEmailRoute,
  AuthenticatedAdminMarketingPushRoute: AuthenticatedAdminMarketingPushRoute,
  AuthenticatedAdminMarketingSmsRoute: AuthenticatedAdminMarketingSmsRoute,
  AuthenticatedAdminMarketingWhatsappRoute:
    AuthenticatedAdminMarketingWhatsappRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  ResultsRoute: ResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
